apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "springboot-restful-template"
  annotations:
    github.com/project-slug: 'StollieBackstageTesting/gs-rest-service'
spec:
  type: restful
  
  lifecycle: experimental
  owner: user:stolliemods
  system: examples
  definition: 
    $text: ./open-api-spec.yaml